<ul class="nav flex-column">    <#-- col-sm-2 -->
    <li class="nav-item">
        <a class="nav-link active" href="#">Математика</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Русский язык</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Окружающий мир</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Дополнительно</a>
    </li>
</ul>